routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



 /*
 GET => account.index
 GET => account.create - form create
 POST => account.store - when submit form create
 GET => account.show - detail
 GET => account.edit - form update
 PUT => account.update - when submit
 DELETE => account.destroy - when delete


*/
Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/about', 'HomeController@about')->name('home.about');
Route::get('/shop', 'HomeController@shop')->name('home.shop');
Route::get('/{slug}', 'HomeController@showCategory')->name('home.showCategory');
Route::get('/contact', 'HomeController@contact')->name('home.contact');

Route::group(['prefix'=>'cart'], function(){
    Route::get('view', 'CartController@view')->name('cart.view');
    Route::get('add/{id}', 'CartController@add')->name('cart.add');
    Route::get('remove/{id}', 'CartController@remove')->name('cart.remove');
    Route::get('update/{id}', 'CartController@update')->name('cart.update');
    Route::get('clear', 'CartController@clear')->name('cart.clear');
});
// , 'middleware'=>'auth'
Route::group(['prefix'=>'admin', 'middleware'=>'auth'], function(){
    Route::get('/', 'AdminController@dashboard')->name('admin.dashboard');
    Route::get('/file', 'AdminController@file')->name('admin.file');
    Route::get('/logout', 'AdminController@logout')->name('logout');

    Route::resources([
        'category' => 'CategoryController',
        'product' => 'ProductController',
        'banner' => 'BannerController',
        'account' => 'AccountController',
        'blog' => 'BlogController',
        'order' => 'OrderController',
        'user' => 'UserController',
    ]);

});
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
// Route::get('/{slug}', 'HomeController@view')->name('view');

Route::get('admin/login', 'AdminController@login')->name('login');
Route::post('admin/login', 'AdminController@post_login')->name('login');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $table = 'category';
    public $primaryKey = 'id';
    // public $timestamps = false;
    protected $fillable = [
        'name', 'slug', 'status', 'prioty'
    ];
// join 1-n
    public function product(){
        return $this->hasMany(Product::class,'idCategory', 'id');
    }

    // global scope
    public function scopeSearch($query){
        if($key = request()->key){
            $query = $query->where('name', 'like', "%$key%");
        }
        return $query;    
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\Category\StoreRequest;
use App\Http\Requests\Category\UpdateRequest;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $key = $request->get('key');
        $data = Category::orderBy('created_at', 'DESC')->search()->paginate(3);
        return view('admin.category.index', compact('data', 'key'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        //
        // $request->validate([
        //     'name' => 'required|unique:category',
        //     'prioty' => 'required'
        // ],[
        //     'name.required' => 'Tên danh mục không để trống',
        //     'prioty.required' => 'Thứ tự ưu tiên không để trống',
        //     'name.unique' => 'Danh mục này đã có trong CSDL',
        // ]);
        if(Category::create($request->all())){
            return redirect()->route('category.index')->with('success','Add new category success!');
        }
        // $category = new Category();
        // $category -> name = $request-> get('name');
        // $category -> status = $request->get('status');
        // $category -> prioty = $request->get('prioty');
        // $category -> save();
        // return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Category $category)
    {
        //
        // $request->validate([
        //     'name' => 'required|unique:category,name,' .$category->id,
        //     'prioty' => 'required'
        // ],[
        //     'name.required' => 'Tên danh mục không để trống',
        //     'prioty.required' => 'Thứ tự ưu tiên không để trống',
        //     'name.unique' => 'Danh mục này đã có trong CSDL',
        // ]);

        $category->update($request->only('name','status','prioty'));
        return redirect()->route('category.index')->with('update','Update Success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
        if($category->product->count() > 0){
            return redirect()->route('category.index')->with('error', 'Danh mục đang còn sản phẩm');
        }else{
            $category->delete();
            return redirect()->route('category.index')->with('success','Xóa thành công!');
        }
        
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin')
@section('main')

<h1>Add Category</h1>
<div class="container">
    <form action="{{route('category.store')}}" class="was-validated" method="POST">
        @csrf
        {{-- @method('PUT') --}}
      <div class="form-group">
        <label for="uname">Name:</label>
        <input type="text" class="form-control" id="name" placeholder="Name..." name="name">
        @error('name')
        <small class="help-block">{{$message}}</small>
        @enderror
      </div>
      <div class="form-group">
        <label for="uname">Slug:</label>
        <input type="text" class="form-control" id="slug" placeholder="Slug here..." name="slug">
        @error('slug')
        <small class="help-block">{{$message}}</small>
        @enderror
      </div>
      <div class="form-group">
        <label for="pwd">Status:</label>
        <div>
            <input type="radio" checked value="1" id="status" name="status"> <label for="pwd">Public</label>
            <input type="radio" value="0" id="status" name="status"> <label for="pwd">Private</label>
        </div>
      </div>
      <div class="form-group">
        <label for="uname">Prioty:</label>
        <input type="text" class="form-control" id="name" placeholder="Prioty..." name="prioty">
        @error('prioty')
          <small class="help-block">{{$message}}</small>
      @enderror
      </div>
      <button type="submit" class="btn btn-primary">Add</button>
    </form>
  </div>

@stop()

@section('js')
  <script src="{{ url('ad') }}/js/slug.js"></script>
@stop()

resources/views/admin/category/edit.blade.php
@extends('layouts.admin')
{{-- @section('title', 'Edit Category') --}}
@section('main')

    <h1>Update Category</h1>
    <div class="container">
        <form action="{{ route('category.update', $category->id) }}" class="was-validated" method="POST">
            @csrf
            @method('PUT')
            <input type="hidden" value="{{ $category->id }}" name="id">
            <div class="form-group">
                <label for="uname">Name:</label>
                <input type="text" value="{{ $category->name }}" class="form-control" name="name" id="name"
                    placeholder="Name...">
                @error('name')
                    <small class="help-block">{{ $message }}</small>
                @enderror
            </div>
            <div class="form-group">
                <label for="pwd">Status:</label>
                <div>
                    <input type="radio" checked value="1" id="status" name="status"> <label for="pwd">Public</label>
                    <input type="radio" value="0" id="status" name="status"> <label for="pwd">Private</label>
                </div>
            </div>
            <div class="form-group">
                <label for="uname">Prioty:</label>
                <input type="number" value="{{ $category->prioty }}" class="form-control" id="prioty"
                    placeholder="Prioty..." name="prioty">
                @error('prioty')
                    <small class="help-block">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>

@stop();

resources/views/admin/category/index.blade.php
@extends('layouts.admin')
@section('main')

<h1>List Category</h1>
<form class="form-inline" method="get">
    @csrf
    <div class="form-group">
        <input type="text" name="key" value="{{$key}}" class="form-control" placeholder="Enter name..." aria-describedby="helpId">
    </div>
    <button class="btn btn-primary">
        <i class="fas fa-search"></i>
    </button>
</form>
<hr>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Total Product</th>
                <th>Status</th>
                <th>Create Category</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data as $cat)    
            <tr>
                <td>{{$cat->id}}</td>
                <td>{{$cat->name}}</td>
                <td>{{$cat->product ->count()}}</td>
                <td>
                    @if($cat->status == 0)
                        <span class="badge badge-danger">Private</span>
                    @else
                        <span class="badge badge-success">Private</span>
                    @endif
                </td>
                <td>{{$cat->created_at}}</td>
                {{-- text-right --}}
                <td class="">
                    <a href="{{route('category.edit', $cat->id)}}" class="btn btn-success">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="{{route('category.destroy', $cat->id)}}" class="btn btn-danger btndelete">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
                
            </tr>
        @endforeach    
        </tbody>
    </table>
    <form action="" method="POST" id="form-delete">
        @csrf
        @method('DELETE')
    </form>
    <hr>
    <div class="">
        {{$data -> appends(request()->all())->links()}}
    </div>
    @stop()

    @section('js')

        <script>
            $('.btndelete').click(function(ev){
                ev.preventDefault();
                var _href = $(this).attr('href');

                $('form#form-delete').attr('action', _href);
                if(confirm('Are you sure you want to delete this category')){
                    $('form#form-delete').submit();
                }
            })
        </script>


@stop()